# Generated by Django 3.2 on 2021-10-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breakout_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('stock_name', models.CharField(max_length=50)),
                ('close', models.DecimalField(decimal_places=2, max_digits=10)),
                ('boxsize', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sl', models.DecimalField(decimal_places=2, max_digits=10)),
                ('breakout', models.BooleanField()),
            ],
        ),
    ]
